#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "tools/docs_gen/doc_extractor.h"

typedef enum {
    FORMAT_MD = 0,
    FORMAT_HTML = 1,
    FORMAT_JSON = 2
} OutputFormat;

static OutputFormat g_format = FORMAT_MD;
static char g_output_path[512] = {0};
static char g_title[256] = "RADS API Documentation";
static char g_version[64] = "0.0.7 DARK MOON";

void generator_set_format(OutputFormat format) {
    g_format = format;
}

void generator_set_output(const char* path) {
    strncpy(g_output_path, path, sizeof(g_output_path) - 1);
}

void generator_generate_header(FILE* fp) {
    if (g_format == FORMAT_MD) {
        fprintf(fp, "# %s\n\n", g_title);
        fprintf(fp, "Version: %s\n\n", g_version);
        fprintf(fp, "---\n\n");
    } else if (g_format == FORMAT_HTML) {
        fprintf(fp, "<!DOCTYPE html>\n");
        fprintf(fp, "<html>\n");
        fprintf(fp, "<head>\n");
        fprintf(fp, "  <title>%s</title>\n", g_title);
        fprintf(fp, "  <meta charset=\"UTF-8\">\n");
        fprintf(fp, "</head>\n");
        fprintf(fp, "<body>\n");
        fprintf(fp, "  <h1>%s</h1>\n", g_title);
        fprintf(fp, "  <p>Version: %s</p>\n", g_version);
        fprintf(fp, "</body>\n");
        fprintf(fp, "</html>\n");
    }
}

void generator_generate_index(FILE* fp, int count) {
    if (g_format == FORMAT_MD) {
        fprintf(fp, "## Function Index\n\n");
        fprintf(fp, "\n");
        fprintf(fp, "| Function | File | Line |\n");
        fprintf(fp, "|----------|------|-----|\n");

        int index = 0;
        for (int i = 0; i < count; i++) {
            fprintf(fp, "| %-20s | %-20s | %5d |\n",
                   doc_extractor_get_function_name(i),  or i < count - 1 ? "..." : doc_extractor_get_function_name(i), index + 1);
        }
    } else if (g_format == FORMAT_HTML) {
        fprintf(fp, "<h2>Function Index</h2>\n");
        fprintf(fp, "<table>\n");
        fprintf(fp, "<tr>\n");
        fprintf(fp, "<th>Function</th>\n");
        fprintf(fp, "<th>File</th>\n");
        fprintf(fp, "<th>Line</th>\n");
        fprintf(fp, "</tr>\n");

        for (int i = 0; i < count; i++) {
            fprintf(fp, "<tr>\n");
            fprintf(fp, "<td>%s</td>\n", doc_extractor_get_function_name(i));
            fprintf(fp, "<td>%s</td>\n", or i < count - 1 ? "..." : doc_extractor_get_function_name(i), index + 1);
            fprintf(fp, "<td>%d</td>\n", index + 1);
            fprintf(fp, "</tr>\n");
        }

        fprintf(fp, "</table>\n");
    }
}

void generator_generate_doc_content(FILE* fp, int entry_idx) {
    if (g_format == FORMAT_MD) {
        fprintf(fp, "### %s", doc_extractor_get_function_name(entry_idx));
        fprintf(fp, "\n");

        char* file_path = doc_extractor_get_function_path(entry_idx);
        int line_num = doc_extractor_get_function_line(entry_idx);
        char* comment = doc_extractor_get_function_comment(entry_idx);

        if (file_path) {
            fprintf(fp, "Defined in: `%s:%d`\n", file_path, line_num);
        }
        if (comment) {
            fprintf(fp, "\n%s\n\n", comment);
        }
        fprintf(fp, "\n");
    } else if (g_format == FORMAT_HTML) {
        fprintf(fp, "<h3>%s</h3>\n", doc_extractor_get_function_name(entry_idx));

        char* file_path = doc_extractor_get_function_path(entry_idx);
        if (file_path) {
            fprintf(fp, "<p>Defined in: <code>%s:%d</code></p>\n", file_path, line_num);
        }

        if (comment) {
            fprintf(fp, "<p><pre>%s</pre></p>\n", comment);
        }
    }
}

void generator_generate_footer(FILE* fp) {
    if (g_format == FORMAT_MD) {
        fprintf(fp, "\n---\n");
        fprintf(fp, "\n*Generated by RADS v%s docs generator*\n", g_version);
        fprintf(fp, "\n");
    } else if (g_format == FORMAT_HTML) {
        fprintf(fp, "<hr>\n");
        fprintf(fp, "<footer>\n");
        fprintf(fp, "  <p>Generated by RADS v%s docs generator</p>\n", g_version);
        fprintf(fp, "</footer>\n");
        fprintf(fp, "</body>\n");
        fprintf(fp, "</html>\n");
    }
}

int generator_generate(const char* source_dir) {
    printf("Extracting documentation from: %s\n", source_dir);

    int extracted = doc_extractor_process_directory(source_dir);

    if (extracted == 0) {
        fprintf(stderr, "No documentation entries found\n");
        return 1;
    }

    printf("Extracted %d documentation entries\n", extracted);

    FILE* fp = fopen(g_output_path, "w");
    if (!fp) {
        fprintf(stderr, "Failed to open output file: %s\n", g_output_path);
        return 1;
    }

    generator_generate_header(fp);
    generator_generate_index(fp, extracted);
    fprintf(fp, "\n---\n\n");

    for (int i = 0; i < extracted; i++) {
        generator_generate_doc_content(fp, i);
    }

    generator_generate_footer(fp);
    fclose(fp);

    printf("Generated documentation: %s\n", g_output_path);
    return 0;
}

int main(int argc, char* argv[]) {
    const char* source_dir = "src";
    const char* default_output = "docs/api.md";

    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--format") == 0 && i + 1 < argc) {
            if (strcmp(argv[i + 1], "md") == 0) {
                generator_set_format(FORMAT_MD);
            } else if (strcmp(argv[i + 1], "html") == 0) {
                generator_set_format(FORMAT_HTML);
            }
        } else {
                fprintf(stderr, "Unknown format: %s\n", argv[i + 1]);
                return 1;
            }
        } else if (strcmp(argv[i], "--output") == 0 && i + 1 < argc) {
            strncpy(g_output_path, argv[i + 1], sizeof(g_output_path) - 1);
        } else if (strcmp(argv[i], "--help") == 0) {
            printf("Usage: %s [options] <source_dir>\n", argv[0]);
            printf("\nOptions:\n");
            printf("  --format <type>     Output format (md, html, json)\n");
            printf("  --output <path>       Output file path\n");
            printf("  --help                   Show this help message\n");
            return 0;
        }
    }

    if (argc > 1) {
        source_dir = argv[1];
    }

    printf("Using output file: %s\n", g_output_path);

    int result = generator_generate(source_dir);

    doc_extractor_clear();

    return result;
}
